"""Dara WIP preview — read-only validation of parquet files.

Owner: Dara (@data-engineer)
Story: T002.0a (in-progress, PID 12608 still materializing)

Purpose
-------
Generate a PREVIEW manifest (``data/manifest_PREVIEW.csv``) from parquet files
ALREADY ON DISK. This is a FIXTURE for Dex to consume during T002.0b
development (``feed_parquet.py``) — it is **NOT** a custodial artifact and
must be DISCARDED once ``scripts/materialize_parquet.py`` finishes and writes
the real ``data/manifest.csv``.

Operational constraints
-----------------------
* DO NOT touch PID 12608 (materialize process still running).
* DO NOT touch ``data/manifest.csv`` (official, chain-of-custody protected).
* DO NOT touch any ``*.tmp`` leftovers (Riven policy — only cleanup post-kill).
* Read-only over parquet files; compute sha256, row counts, ts min/max, phase.

Output
------
``data/manifest_PREVIEW.csv`` with columns:
    path, rows, sha256, start_ts_brt, end_ts_brt, ticker, phase,
    generated_at_brt, SOURCE

Where ``SOURCE="dara_preview_wip_NOT_CUSTODIAL"`` is a sentinel string so that
any downstream consumer loading this file by mistake trips on it.
"""

from __future__ import annotations

import csv
import hashlib
import re
import sys
from datetime import datetime
from pathlib import Path

# Local import — reuse classify_phase from the materializer (no duplication).
_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from materialize_parquet import classify_phase  # noqa: E402

REPO_ROOT = _SCRIPTS_DIR.parent
IN_SAMPLE_DIR = REPO_ROOT / "data" / "in_sample"
PREVIEW_PATH = REPO_ROOT / "data" / "manifest_PREVIEW.csv"

EXPECTED_SCHEMA_FIELDS = (
    "timestamp",
    "ticker",
    "price",
    "qty",
    "aggressor",
    "buy_agent",
    "sell_agent",
)

PREVIEW_COLUMNS = (
    "path",
    "rows",
    "sha256",
    "start_ts_brt",
    "end_ts_brt",
    "ticker",
    "phase",
    "generated_at_brt",
    "SOURCE",
)

PREVIEW_HEADER_COMMENT = (
    "# WIP PREVIEW - NOT CUSTODIAL MANIFEST. Generated by "
    "scripts/_preview_manifest_dara.py while PID 12608 still materializes.\n"
    "# Purpose: fixture for Dex (T002.0b) feed_parquet.py development.\n"
    "# DISCARD this file once scripts/materialize_parquet.py writes the real "
    "data/manifest.csv.\n"
    "# SOURCE column sentinel: dara_preview_wip_NOT_CUSTODIAL\n"
)

# Matches names like 'wdo-2024-07.parquet'.
_PARQUET_NAME_RE = re.compile(r"^(?P<ticker>[a-z]+)-(?P<year>\d{4})-(?P<month>\d{2})\.parquet$")


def _sha256_file(path: Path) -> str:
    """Streaming sha256 over the file (1 MiB chunks)."""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _iter_parquets(root: Path):
    """Yield parquet Paths in deterministic (year, month) order."""
    discovered = []
    for year_dir in sorted(root.glob("year=*")):
        if not year_dir.is_dir():
            continue
        for month_dir in sorted(year_dir.glob("month=*")):
            if not month_dir.is_dir():
                continue
            for pq_file in sorted(month_dir.glob("*.parquet")):
                discovered.append(pq_file)
    return discovered


def _validate_schema(schema, path: Path) -> tuple[bool, str]:
    """Return (ok, reason)."""
    got = tuple(schema.names)
    if got != EXPECTED_SCHEMA_FIELDS:
        return (
            False,
            f"schema mismatch at {path}: got {got}, expected {EXPECTED_SCHEMA_FIELDS}",
        )
    return (True, "")


def main() -> int:
    try:
        import pyarrow.parquet as pq  # type: ignore[import-untyped]
    except ImportError as exc:
        print(f"FATAL: pyarrow required: {exc}", file=sys.stderr)
        return 1

    parquets = _iter_parquets(IN_SAMPLE_DIR)
    if not parquets:
        print(f"[preview] no parquets found under {IN_SAMPLE_DIR}", file=sys.stderr)
        return 1

    print(f"[preview] found {len(parquets)} parquet file(s)")
    generated_at = datetime.now().isoformat(timespec="seconds")

    rows_out: list[dict[str, str]] = []
    anomalies: list[str] = []

    for pq_path in parquets:
        rel = pq_path.relative_to(REPO_ROOT).as_posix()
        print(f"[preview] inspecting {rel}")

        # Parse filename for ticker / year / month.
        m = _PARQUET_NAME_RE.match(pq_path.name)
        if not m:
            anomalies.append(f"{rel}: filename does not match pattern")
            continue
        file_ticker = m.group("ticker").upper()

        # Metadata (num_rows is cheap — footer only).
        try:
            meta = pq.read_metadata(str(pq_path))
            num_rows = int(meta.num_rows)
        except Exception as exc:
            anomalies.append(f"{rel}: read_metadata failed: {exc}")
            continue

        if num_rows == 0:
            anomalies.append(f"{rel}: num_rows == 0 (empty parquet)")

        # Schema (cheap).
        try:
            schema = pq.read_schema(str(pq_path))
        except Exception as exc:
            anomalies.append(f"{rel}: read_schema failed: {exc}")
            continue

        ok, reason = _validate_schema(schema, pq_path)
        if not ok:
            anomalies.append(reason)
            continue

        # timestamp min / max — read only that column.
        try:
            ts_table = pq.read_table(str(pq_path), columns=["timestamp"])
            ts_col = ts_table.column("timestamp")
            ts_py = ts_col.to_pylist()
            if not ts_py:
                anomalies.append(f"{rel}: empty timestamp column")
                continue
            start_ts = min(ts_py)
            end_ts = max(ts_py)
        except Exception as exc:
            anomalies.append(f"{rel}: timestamp read failed: {exc}")
            continue

        # Phase classification via imported materializer function.
        try:
            phase = classify_phase(start_ts.date(), end_ts.date())
        except ValueError as exc:
            anomalies.append(f"{rel}: classify_phase error: {exc}")
            phase = "UNKNOWN"

        # sha256 via hashlib (no certutil).
        try:
            digest = _sha256_file(pq_path)
        except Exception as exc:
            anomalies.append(f"{rel}: sha256 failed: {exc}")
            continue

        rows_out.append({
            "path": rel,
            "rows": str(num_rows),
            "sha256": digest,
            "start_ts_brt": start_ts.isoformat(),
            "end_ts_brt": end_ts.isoformat(),
            "ticker": file_ticker,
            "phase": phase,
            "generated_at_brt": generated_at,
            "SOURCE": "dara_preview_wip_NOT_CUSTODIAL",
        })
        print(
            f"[preview]   rows={num_rows} phase={phase} "
            f"ts=[{start_ts.isoformat()} .. {end_ts.isoformat()}] "
            f"sha256={digest[:16]}..."
        )

    # Write preview.
    PREVIEW_PATH.parent.mkdir(parents=True, exist_ok=True)
    with PREVIEW_PATH.open("w", encoding="utf-8", newline="") as fh:
        fh.write(PREVIEW_HEADER_COMMENT)
        writer = csv.DictWriter(
            fh, fieldnames=list(PREVIEW_COLUMNS), lineterminator="\n"
        )
        writer.writeheader()
        for row in rows_out:
            writer.writerow({k: row.get(k, "") for k in PREVIEW_COLUMNS})

    print(f"[preview] wrote {len(rows_out)} row(s) -> {PREVIEW_PATH}")
    if anomalies:
        print("[preview] ANOMALIES DETECTED:", file=sys.stderr)
        for a in anomalies:
            print(f"[preview]   - {a}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
